server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
spring:
  application:
    name: api-gateway

  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        - id: authentication-service
          uri: http://localhost:8091
          predicates:
            - Path=/authentication-service/**
          filters:
            - RewritePath=/authentication-service(?<segment>/?.*), $\{segment}
        - id: user-service
          uri: http://localhost:8099
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service(?<segment>/?.*), $\{segment}
        - id: CART-SERVICE
          uri: http://localhost:8090
          predicates:
            - Path=/cart-service/**
          filters:
            - RewritePath=/cart-service(?<segment>/?.*), $\{segment}
        - id: PRODUCT-SERVICE
          uri: http://localhost:8083
          predicates:
            - Path=/product-service/**
          filters:
            - RewritePath=/product-service(?<segment>/?.*), $\{segment}
        - id: RECOMMENDATION-SERVICE
          uri: http://localhost:8096
          predicates:
            - Path=/recommendation-service/**
          filters:
            - RewritePath=/recommendation-service(?<segment>/?.*), $\{segment}
        - id: SHOP-SERVICE
          uri: http://localhost:8097
          predicates:
            - Path=/shop-service/**
          filters:
            - RewritePath=/shop-service(?<segment>/?.*), $\{segment}





#spring:
#  main:
#    web-application-type: reactive
#  cloud:
#    gateway:
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods: "*"
#            allowedHeaders: "*"

